config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  get 'bright_events/user', to: 'bright_events#user_events', as: :user_bright_events
  resources :bright_events do
    member do
      delete :purge_image
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bright_event.rb
class BrightEvent < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validates :location, presence: true
  validates :cost, presence: true

  has_one_attached :image
  belongs_to :user

  validates :image, content_type: { in: %w[image/jpeg image/png image/jpg], message: 'Debe ser un archivo JPEG/PNG' }

  scope :all_events, ->(user) { where('privacy = ? OR user_id = ?', false, user.id) }
  scope :filter_date, ->(from, to) { where(date: from.to_date.beginning_of_day..to.to_date.end_of_day) }
  paginates_per 6

  require 'csv'
  def self.to_csv(events)
    attributes = %w[title description date location cost]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      events.each do |event|
        csv << attributes.map { |attr| event.send(attr) }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable 

  has_many :bright_events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_bright_events_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username])

    devise_parameter_sanitizer.permit(:account_update, keys: %i[username])
  end
end

app/controllers/bright_events_controller.rb
class BrightEventsController < ApplicationController
  before_action :find_event, only: %i[show edit update destroy purge_image]

  def index
    @events = BrightEvent.all_events(current_user).page params[:page]
    filters if filters?
    download_csv if params[:format] == 'csv'
  end

  def show; end

  def new
    @event = BrightEvent.new
  end

  def user_events
    @events = current_user.bright_events.page params[:page]
    filters if filters?
    download_csv if params[:format] == 'csv'
  end

  def create
    @event = current_user.bright_events.create(event_params)

    if @event.save
      EventReminderJob.set(wait_until: @event.reminder).perform_later(@event.id, @event.updated_at)
      redirect_to user_bright_events_path
    else
      flash[:error] = @event.errors.full_messages.to_sentence
      redirect_to new_bright_event_path
    end
  end

  def edit; end

  def purge_image
    @event.image.destroy
    redirect_back fallback_location: edit_bright_event_path(@event.id), notice: 'Imagen eliminada con éxito'
  end

  def update
    if @event.update(event_params)
      EventReminderJob.set(wait_until: @event.reminder).perform_later(@event.id, @event.updated_at)
      redirect_to user_bright_events_path
    else
      flash[:error] = @event.errors.full_messages.to_sentence
      redirect_to edit_bright_event_path
    end
  end

  def destroy
    @event.destroy

    redirect_to bright_events_path
  end

  private

  def filters
    @events = @events.filter_date(params[:date_from], params[:date_to]) if date_filter?
    if params[:privacy] == 'Todos' && params[:privacy].present?
      @events = @events.all_events(current_user)
    elsif params[:privacy] == 'true' && params[:privacy].present?
      @events = current_user.bright_events.where(privacy: true).page params[:page]
    elsif params[:privacy] == 'false' && params[:privacy].present?
      @events = @events.where(privacy: params[:privacy])

      @events
    end

    @events
  end

  def event_params
    params.require(:bright_event).permit(:title, :description, :date, :location, :cost, :image, :privacy, :reminder)
  end

  def date_filter?
    params[:date_from].present? && params[:date_to].present?
  end

  def filters?
    params[:date_from].present? || params[:date_to].present? || params[:privacy].present?
  end

  def find_event
    @event = BrightEvent.find(params[:id])
  end

  def download_csv
    respond_to do |format|
      format.html
      format.csv { send_data BrightEvent.to_csv(@events), filename: "eventos-#{Date.today}.csv" }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bright_events_helper.rb
module BrightEventsHelper
  def filters_action
    if action_name != 'index'
      user_bright_events_path
    else
      bright_events_path
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bright_events/_action_bar.html.erb
<div class='action_bar'>
  <div>
    <%= link_to new_bright_event_path , class: 'btn btn-warning' do %>
      <i class="uil uil-plus"></i>
      <span>Agregar evento</span>
    <% end %>
  </div>
  <%= render 'filters' %>
</div>

app/views/bright_events/_cards_container.html.erb
<%= link_to "Exportar Eventos", { action: "#{action_name}", format: "csv" }.merge(params.permit(:privacy, :date_from, :date_to))%>
<div class="cards-container">
  <% @events.each do |event|%>
    <div class="card">
      <div class="card-header" style="background-image: url(<%= url_for(event.image) if event&.image.attached? %>)">
      </div>
      <div class="card-body">
        <div class="info-event">
          <h2><%= event.title %></h2>
          <h3><%= event.user.username %></h3>
          <h4><%= Time.at(event.date).strftime('%d/%m/%Y') %></h4>
          <h5><%= event.location %></h5>
        </div>
        <p><%= event.description %></p>
      </div>
      <div class="card-footer">
        <p>$ <%= event.cost %> MXN</p>
        <p><%= event.privacy ? 'Privado' : 'Público' %></p>
      </div>
      <% if action_name == 'user_events' %>
        <div class="card-footer">
          <div class="action">
            <%= link_to edit_bright_event_path(event.id) do %>
              <label for="">Editar</label>
              <i class="uil uil-pen"></i>
            <% end %>
          </div>
          <div class="action">
            <%= link_to bright_event_path(event), data: { turbo_confirm: '¿Estás seguro de que deseas eliminar esto?', turbo_method: :delete } do %>
              <label for="">Eliminar</label>
              <i class="uil uil-trash-alt"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<%= paginate @events if @events %>

app/views/bright_events/_filters.html.erb
<div class='filter' data-controller="date-picker">
  <h3>Filtros</h3>
  <%= form_tag(filters_action, method: :get) do %>
    <div class="form-group">
      <%= label_tag 'privacy', 'Privacidad: ' %>
      <%= select_tag 'privacy',
                options_for_select([['Todos', 'Todos'], ['Público', false], ['Privado', true]],
                                    params[:privacy]),
                  class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= label_tag 'date_from', 'De:' %>
      <%= date_field_tag :date_from, params[:date_from], class: 'form-control', 'data-date-picker-target': 'dateFrom', 'data-action': 'change->date-picker#updateMinDate' %>
    </div>

    <div class="form-group">
      <%= label_tag 'date_to', 'A:' %>
      <%= date_field_tag :date_to, params[:date_to], class: 'form-control', 'data-date-picker-target': 'dateTo' %>
    </div>
    <%= submit_tag 'Filtrar', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/bright_events/_form.html.erb
<%= form_for (@event) do |f| %>
  <%= f.text_field :title, placeholder: 'Título', value: @event.title, required: true %>
  <%= f.text_field :description, placeholder: 'Descripción', value: @event.description, required: true %>
  <%= f.date_field :date, id: 'event_date', placeholder: 'Fecha', value: @event.date, min: 0.days.ago, required: true, data: { event_form_target: "date", action: "change->event-form#updateMaxDate" } %>
  <%= f.text_field :location, placeholder: 'Ubicación', value: @event.location, required: true %>
  <%= f.number_field :cost, in: 0.00..1000000.00, step: 0.01, placeholder: 'Precio', value: @event.cost, required: true %>
  <div>
    <p>¿Quieres que tu evento sea...?</p>
    <%= f.label :privacy, 'Privado' %>
    <%= f.radio_button :privacy, true %>
    <%= f.label :privacy, 'Público' %>
    <%= f.radio_button :privacy, false %>
  </div>
  <% if action_name == 'edit' && @event.image.attached? %>
    <div class="image-container">
      <%= link_to purge_image_bright_event_path(@event), method: :delete, data: { turbo_method: :delete } do %>
        <i class="fas fa-trash-alt"></i> Eliminar imagen
      <% end %>
      <%= image_tag @event.image.representation(resize_to_limit: [300, 300]) if @event.image.representable? %> 
    </div>
  <% end %>
  <%= f.file_field :image, value: @event.image, accept:"image/png, image/jpg, image/jpeg" %>
  <p>Configura el recordatorio para tu evento:</p>
  <%= f.datetime_field :reminder, id: 'event_reminder', value: @event.reminder, min: Time.current.strftime("%Y-%m-%dT%H:%M"), max: @event.date ? @event.date.strftime("%Y-%m-%dT%H:%M") : nil, data: { event_form_target: "reminder" } %>
  <%= f.submit 'Guardar cambios', class: 'btn btn-submit' %>
<% end %>

app/views/bright_events/edit.html.erb
<div class="form-wrap">
  <%= link_to user_bright_events_path, class: 'btn btn-return' do %>
    <i class="uil uil-arrow-left"></i>
  <% end %>  
  <div class="form-container">
    <h1>Editar Evento</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/bright_events/index.html.erb
<div class="event-list-container">
  <h1>Todos los Eventos</h1>
  <%= render 'action_bar' %>
  <%= render 'cards_container' %>
</div>

app/views/bright_events/new.html.erb
<div class="form-wrap">
  <%= link_to user_bright_events_path, class: 'btn btn-return' do %>
    <i class="uil uil-arrow-left"></i>
  <% end %>  
  <div class="form-container">
    <h1>Crear Evento</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/bright_events/user_events.html.erb
<div class="event-list-container">
  <h1>Mis eventos</h1>
  <%= render 'action_bar' %>
  <%= render 'cards_container' %>
</div>

app/views/home/index.html.erb
<div class="hero">
  <h1>Sistema de Gestion de Eventos</h1>
  <%= image_tag('defaults/hero.webp') %>

  <%= link_to "Iniciar", new_user_session_path , class: 'btn' %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p>© BrightCoders Equipo 35. Todos los derechos reservados.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag('defaults/logo.webp') %>
    <% end %>
  </div>
  <% if current_user %>
    <%= link_to 'Todos los eventos', bright_events_path %>
    <%= link_to 'Mis eventos', user_bright_events_path %>
    <%= link_to 'Cerrar Sesion', destroy_user_session_path, data: { turbo_method: :delete } %>
  <% else %>
    <%= link_to 'Inicia Sesion', new_user_session_path %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S5a1AdministradorDeEventosTeam03S5a1AdministradorDeEventos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Ubuntu">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% if flash[:error] || flash[:notice] %>
      <div class="alert-container">
        <p class="alert-<%= flash[:error] ? 'error' : 'notice' %>">
          <%= flash[:error] || flash[:notice] %>
        </p>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>